/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import { GetServerSideProps } from 'next'

import { createDb, createObjects } from '../services/util'
import { Iprops } from '../model/Interface'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'
import GpusTable from '../components/GpusTable'

export const getServerSideProps: GetServerSideProps = async () => {
  const apiUri = String(process.env.API_URI)
  const data = await createDb(apiUri)
  return {
    props: { data }
  }
}

const Home: NextPage<Iprops> = ({ data }: Iprops) => {
  const [Loading, setLoading] = useState(true)
  const GpusRaw = createObjects(data)
  const [Gpus, setGpus] = useState(GpusRaw)

  useEffect(() => {
    if (Gpus.length > 0) {
      setLoading(false)
    }
  }, [Gpus, Loading])

  return (
    <>
      <Head>
        <title>KPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400;600;700&display=swap" rel="stylesheet" />
      </Head>
      <div className={'main flex flex-col w-[99.1%] h-full font-fancy font-normal text-text bg-bgMain z-0'}>
        <Header />
        <div className="flex flex-row w-[100%]">
          <Sidebar GpusRaw={GpusRaw} Gpus={Gpus} setGpus={setGpus} />
          <GpusTable Gpus={Gpus} />
        </div>
      </div>
    </>
  )
}

export default Home
